-- sample setup script for MySQL DAL tests database

CREATE DATABASE `dal_tests_mysql` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE USER 'DALTSTADMIN'@'%' IDENTIFIED BY 'ha';
CREATE USER 'DALTSTRUNTIME'@'%' IDENTIFIED BY 'hr';


GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE ROUTINE, ALTER ROUTINE ON `dal_tests_mysql`.* TO 'DALTSTADMIN'@'%';
GRANT SELECT ON `information_schema`.* TO 'DALTSTADMIN'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE ROUTINE, ALTER ROUTINE ON `dal_tests_mysql`.* TO 'DALTSTRUNTIME'@'%';
GRANT SELECT ON `information_schema`.* TO 'DALTSTRUNTIME'@'%';
