/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Data;
using OutSystems.HubEdition.DatabaseProvider.DB2ZOS.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.IntrospectionService;
using OutSystems.RuntimeCommon;

namespace OutSystems.HubEdition.DatabaseProvider.DB2ZOS.IntrospectionService {
    public class DB2ZOSIntrospectionService : BaseIntrospectionService {

        private readonly string paramPrefix;

        public DB2ZOSIntrospectionService(IDatabaseServices databaseServices) : base(databaseServices) {
            paramPrefix = databaseServices.ExecutionService.ParameterPrefix;
        }
        

        /// <summary>
        /// The DB2 architecture is Database(s)->Schema(s)->Table(s).
        /// As the user can only connect to a specific Database (which is defined in the configuration)
        /// this method should return a list of the Schemas in that database, which were not created by the system
        /// </summary>
        /// <returns>List with schemas not created by the System</returns>
        public override IEnumerable<IDatabaseInfo> ListDatabases() {
            List<IDatabaseInfo> result = new List<IDatabaseInfo>();            
            string query = "SELECT DISTINCT CREATOR as SCHEMA_NAME FROM SYSIBM.SYSTABLES ";
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {
                IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, query);
                cmd.CommandTimeout = QueryTimeout;
                using (IDataReader reader = cmd.ExecuteReader()) {
                    while (reader.Read()) {                        
                        result.Add(DatabaseServices.ObjectFactory.CreateDatabaseInfo((string)reader["SCHEMA_NAME"]));
                    }
                }
            }
            return result;
        }

        public override IEnumerable<ITableSourceInfo> ListTableSources(IDatabaseInfo database, IsTableSourceToIgnore isTableSourceToIgnore) {
            IList<ITableSourceInfo> tables = new List<ITableSourceInfo>();
            DB2ZOSDatabaseInfo databaseInfo = database as DB2ZOSDatabaseInfo;
            if (databaseInfo == null) {
                return null;
            }
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {

                string sql = "SELECT NAME as TABLE_NAME "
                           + "FROM SYSIBM.SYSTABLES  "
                           + "WHERE TYPE in ('T', 'V', 'P') and CREATOR = '" + database.Identifier + "' ";
                //Console.WriteLine("ListTableSources SQL: " + sql);

                IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, sql);
                cmd.CommandTimeout = QueryTimeout;
                using (IDataReader reader = cmd.ExecuteReader()) {
                    while (reader.Read()) {
                        string tableName = (string)reader["TABLE_NAME"];
                        if (!isTableSourceToIgnore(tableName) && DoesNotContainProblematicChars(tableName))
                        {
                            string qualifiedTableName = GetQualifiedIdentifier(databaseInfo.Database, tableName);
                            tables.Add(new DB2ZOSTableSourceInfo(DatabaseServices, databaseInfo, tableName, qualifiedTableName));
                        }
                    }
                }
            }
            return tables;
        }

        private bool DoesNotContainProblematicChars(String tableName) {
            return !(tableName.Contains("'") ||
                     tableName.Contains("ª") ||
                     tableName.Contains("º") ||
                     tableName.Contains("«") ||
                     tableName.Contains("»") ||
                     tableName.Contains("´") ||
                     tableName.Contains("Ç") ||
                     tableName.Contains("§"));
        }

        private bool DatabaseExists(IDbConnection conn, DB2ZOSDatabaseInfo databaseInfo)
        {
            string query = "SELECT COUNT(*) FROM SYSIBM.SYSTABLES WHERE CREATOR = " + paramPrefix + "schema";
            IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, query);
            cmd.CommandTimeout = QueryTimeout;
            DatabaseServices.ExecutionService.CreateParameter(cmd, paramPrefix + "schema", DbType.String, databaseInfo.Database);
            using (IDataReader reader = cmd.ExecuteReader()) {
                return reader.Read();
            }
        }

        private string GetQualifiedIdentifier(string schema, string tableName) {
            return DatabaseServices.DMLService.Identifiers.EscapeIdentifier(schema) + "." +
                DatabaseServices.DMLService.Identifiers.EscapeIdentifier(tableName);
        }

        public override IEnumerable<ITableSourceColumnInfo> GetTableSourceColumns(ITableSourceInfo tableSource) {
            DB2ZOSTableSourceInfo tableInfo = tableSource as DB2ZOSTableSourceInfo;
            if (tableInfo == null) {
                return null;
            }
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {
                if (!CheckTableExists(conn, tableInfo)) {
                    throw new IntrospectionServiceException("'" + tableSource.DisplayName + "' is not a valid physical table name.");
                }
            }
            return GetColumnsInfo(tableInfo);
        }

        public override IEnumerable<ITableSourceForeignKeyInfo> GetTableSourceForeignKeys(ITableSourceInfo tableSource) {
            DB2ZOSTableSourceInfo tableInfo = tableSource as DB2ZOSTableSourceInfo;
            if (tableInfo == null) {
                return null;
            }
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {
                if (!CheckTableExists(conn, tableInfo)) {
                    throw new IntrospectionServiceException("'" + tableSource.DisplayName +
                                                            "' is not a valid physical table name.");
                }
            }
            return GetForeignKeysInfo(tableInfo);
        }

        private IList<ITableSourceColumnInfo> GetColumnsInfo(DB2ZOSTableSourceInfo tableSource) {
            IList<ITableSourceColumnInfo> columnsInfo = new List<ITableSourceColumnInfo>();
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {                
                string query = @"SELECT COLS.*, 
                                (
                                SELECT PKS.NAME FROM SYSIBM.SYSINDEXES  PKS 
                                INNER JOIN SYSIBM.SYSKEYS KYS ON KYS.IXNAME = PKS.NAME
                                WHERE PKS.TBNAME = COLS.TBNAME AND PKS.CREATOR = COLS.TBCREATOR AND PKS.UNIQUERULE = 'P' AND KYS.COLNAME = COLS.NAME
                                ) as PK_NAME,
                                COL_CHK.CHECKCONDITION as CHECK_CLAUSE,
                                UDTS.ENCODING_SCHEME as ORDERING_ROUT_NAME  
                                FROM SYSIBM.SYSCOLUMNS COLS 
                                INNER JOIN SYSIBM.SYSTABLES TAB ON TAB.NAME = COLS.TBNAME AND TAB.CREATOR = COLS.TBCREATOR 				
                                LEFT JOIN SYSIBM.SYSVIEWDEP VDEP ON TAB.TYPE = 'V' and TAB.CREATOR = VDEP.BCREATOR and TAB.NAME = VDEP.DNAME
                                LEFT JOIN SYSIBM.SYSCHECKDEP DEP ON 
                                  ((TAB.TYPE = 'T' or TAB.TYPE = 'P') and DEP.TBOWNER = TAB.CREATOR and DEP.TBNAME = TAB.NAME and DEP.COLNAME = COLS.NAME)
                                  OR (TAB.TYPE = 'V' and DEP.TBOWNER = VDEP.BCREATOR and DEP.TBNAME = VDEP.BNAME and DEP.COLNAME = COLS.NAME)
                                LEFT JOIN SYSIBM.SYSCHECKS COL_CHK ON 
                                  ((TAB.TYPE = 'T' or TAB.TYPE = 'P') and COL_CHK.TBOWNER = DEP.TBOWNER and COL_CHK.TBNAME = TAB.NAME and COL_CHK.CHECKNAME = DEP.CHECKNAME)
                                  OR (TAB.TYPE = 'V' and COL_CHK.TBOWNER = DEP.TBOWNER and COL_CHK.TBNAME = DEP.TBNAME and COL_CHK.CHECKNAME = DEP.CHECKNAME)
                                LEFT JOIN SYSIBM.SYSDATATYPES UDTS ON UDTS.NAME = COLS.COLTYPE 
                                WHERE (COLS.GENERATED_ATTR is null OR COLS.GENERATED_ATTR <> 'A') and TAB.CREATOR = '" + tableSource.Database.Identifier + "' and TAB.NAME = '" + tableSource.Name.ToUpper() + "'";


				IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, query);
                cmd.CommandTimeout = QueryTimeout;

                using (IDataReader reader = cmd.ExecuteReader()) {
                    int primaryKeyColumnCount = 0;
                    while (reader.Read())
                    {
                        string columnName = (string)reader["NAME"];

                        IDataTypeInfo datatype = CreateDataTypeInfo(reader["COLTYPE"] == DBNull.Value ? null : ((string)reader["COLTYPE"]).Trim(),
                            reader["LENGTH"] == DBNull.Value ? 0 : Convert.ToInt32(reader["LENGTH"]),
                            reader["LENGTH"] == DBNull.Value ? 0 : Convert.ToInt32(reader["LENGTH"]),
                            reader["SCALE"] == DBNull.Value ? 0 : Convert.ToInt32(reader["SCALE"]),
                            reader["CHECK_CLAUSE"] == DBNull.Value ? null : (string)reader["CHECK_CLAUSE"],
                            reader["ORDERING_ROUT_NAME"] == DBNull.Value ? null : (string)reader["ORDERING_ROUT_NAME"],
                            reader["CCSID"] == DBNull.Value ? 0 : Convert.ToInt32(reader["CCSID"]));

                        bool isMandatory = "N".EqualsIgnoreCase((string)reader["NULLS"]);
                        bool isPrimaryKey = (reader["PK_NAME"] != DBNull.Value);
                        var defaultVal = (string)reader["DEFAULT"];
                        bool isAutoGenerated = "I".EqualsIgnoreCase(defaultVal) || "J".EqualsIgnoreCase(defaultVal);

                        DB2ZOSTableSourceColumnInfo info = new DB2ZOSTableSourceColumnInfo(tableSource, columnName, datatype, isMandatory, isPrimaryKey, isAutoGenerated);
                        columnsInfo.Add(info);
                        primaryKeyColumnCount += isPrimaryKey ? 1 : 0;
                    }
                    if (primaryKeyColumnCount > 1) {
                        //we don't support composite primary keys so setting all to non primary key
                        IList<ITableSourceColumnInfo> columnsInfoCopy = new List<ITableSourceColumnInfo>();

                        foreach (ITableSourceColumnInfo c in columnsInfo) {
                            columnsInfoCopy.Add(new DB2ZOSTableSourceColumnInfo(c.TableSource, c.Name, c.DataType, c.IsMandatory, false, c.IsAutoGenerated));
                        }
                        columnsInfo = columnsInfoCopy;
                    }
                }
            }
            return columnsInfo;
        }

        private bool CheckTableExists(IDbConnection conn, DB2ZOSTableSourceInfo tableSource){

			String query = "SELECT  NAME as TABLE_NAME "
							+ "FROM SYSIBM.SYSTABLES "
                            + "WHERE CREATOR = '" + tableSource.Database.Identifier + "' and NAME = '" + tableSource.Name.ToUpper() + "'";

			IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, query);
            cmd.CommandTimeout = QueryTimeout;
            using (IDataReader reader = cmd.ExecuteReader()) {
                return reader.Read();
            }
        }

        private IDataTypeInfo CreateDataTypeInfo(string type, int length, int precision, int scale, String checkClause, String rout_name, int ccsid)
        {
            DBDataType dataType;
            int columnLength = 0, columnDecimals = 0;
            string typeCheck = type.ToLower();
            String boolCheck = "IN(0,1)";
            string extraInfo = "";


            if (typeCheck == "distinct")
                typeCheck = rout_name.ToLower(); //Means that this is a user defined type

            switch (typeCheck) {
                case "smallint":
                case "integer":
                    if (checkClause != null && checkClause.Replace(" ", "").EndsWith(boolCheck)) {
                        dataType = DBDataType.BOOLEAN;
                        columnLength = 2;
                    } else {
                        dataType = DBDataType.INTEGER;
                        columnLength = precision + 1; //Don't know why but, integer and smallints need a +1
                    }
                    break;
                case "bigint":
                    if (checkClause != null && checkClause.Replace(" ", "").EndsWith(boolCheck)) {
                        dataType = DBDataType.BOOLEAN;
                        columnLength = 2;
                    } else {
                        dataType = DBDataType.LONGINTEGER;
                    }
                    break;
                case "decimal":
                case "numeric":
                    if (precision > 28 || scale > 8) {
                        dataType = DBDataType.TEXT;
                        columnLength = precision + 3;
                    } else if (1 <= precision && precision <= 9 && scale == 0) {
                        dataType = DBDataType.INTEGER;
                    } else if (10 <= precision && precision <= 18 && scale == 0) {
                        dataType = DBDataType.LONGINTEGER;
                    } else {
                        dataType = DBDataType.DECIMAL;
                        columnLength = precision;
                        columnDecimals = scale;
                    }
                    extraInfo = "(" + precision + "," + scale + ")";
                    break;
                case "date":
                    dataType = DBDataType.DATE;
                    columnLength = 11; // YYYY-MM-DD + extra character for possible string ending
                    break;                
                case "timestmp":
                    dataType = DBDataType.DATE_TIME;
                    columnLength = 30; // YYYY-MM-DD-hh:mm:ss.nnnnnnnnn + extra character for possible string ending
                    break;
                case "time":
                    dataType = DBDataType.TEXT;
                    columnLength = 9; // hh:mm:ss + extra character for possible string ending
                    break;
                case "char":
                case "varchar":
                case "character":
                case "long varchar":
                    if (ccsid == 65535) {
                        dataType = DBDataType.BINARY_DATA;
                    } else {
                        dataType = DBDataType.TEXT;
                        columnLength = Math.Min(int.MaxValue, length);
                        extraInfo = "(" + length + ")";
                    }
                    break;
                case "varg":
                case "graphic":
                case "vargraphic":
                case "long vargraphic":
                    if (ccsid == 1200) {
                        dataType = DBDataType.TEXT;
                        columnLength = Math.Min(int.MaxValue, length);
                    } else {
                        dataType = DBDataType.UNKNOWN;
                    }
                    
                    break;
                case "clob":
                case "dbclob":
                case "xml":
                    dataType = DBDataType.TEXT;
        	        columnLength = Math.Min(int.MaxValue, length);
                    break;
                case "binary":
                case "varbin":
                case "blob":
                    dataType = DBDataType.BINARY_DATA;
                    break;
                case "decfloat":
                    dataType = DBDataType.TEXT;
                    columnLength = (precision == 16 ? 402 : 6180); // for 16 digits of precision we need 401 (16 + 384 + 2) chars, for 34 digits we need 6179 (34 + 6144 + 2) chars
                    extraInfo = "(" + precision + ")";
                    break;
                case "float":
                    dataType = DBDataType.TEXT;
                    columnLength = (precision == 24 ? 49 : 327); // for 24 bits of precision we need 49 (9 + 38 + 2) chars, for 53 bits of precision we need 327 (17 + 308 + 2) chars
                    extraInfo = "(" + precision + ")";
                    break;
                default:
                    dataType = DBDataType.UNKNOWN;
                    break;
            }
            return new DB2ZOSDataTypeInfo(dataType, type + extraInfo, columnLength, columnDecimals);
        }

        private IList<ITableSourceForeignKeyInfo> GetForeignKeysInfo(DB2ZOSTableSourceInfo tableSource) {
            IList<ITableSourceForeignKeyInfo> foreignKeys = new List<ITableSourceForeignKeyInfo>();
            string query = "SELECT "+
                            "A.RELNAME as FK_NAME, " +
                            "B.COLNAME as FKCOLUMN_NAME," +
                            "A.REFTBCREATOR as PKTABLE_SCHEM, " + 
                            "A.REFTBNAME as PKTABLE_NAME, " +
                            "(SELECT KYS.COLNAME FROM SYSIBM.SYSINDEXES PKS " +
                            "INNER JOIN SYSIBM.SYSKEYS KYS ON KYS.IXNAME = PKS.NAME " +
                            "WHERE PKS.TBNAME = A.REFTBNAME AND PKS.CREATOR = A.CREATOR AND PKS.UNIQUERULE = 'P') " +
                            "as PKCOLUMN_NAME, " +
                            "A.DELETERULE as CASCADE " +
                            "FROM SYSIBM.SYSRELS A, SYSIBM.SYSFOREIGNKEYS B " +
                            "WHERE A.TBNAME = '" + tableSource.Name.ToUpper() + "' " +
                            "AND B.TBNAME = '" + tableSource.Name.ToUpper() + "' " +
                            "AND A.CREATOR = '" + tableSource.Database.Identifier + "' " +
                            "AND B.CREATOR = '" + tableSource.Database.Identifier + "' " +
                            "AND A.RELNAME = B.RELNAME " +
                            "ORDER BY A.RELNAME, B.COLSEQ; ";
            Console.WriteLine("GetForeignKeysInfo, SQL: "+query);
            using (IDbConnection conn = DatabaseServices.TransactionService.CreateConnection()) {
                IDbCommand cmd = DatabaseServices.ExecutionService.CreateCommand(conn, query);
                cmd.CommandTimeout = QueryTimeout;
                using (IDataReader reader = cmd.ExecuteReader()) {
                    while (reader.Read()) {
                        string foreignKeyName = (string)reader["FK_NAME"];
                        string columnName = (string)reader["FKCOLUMN_NAME"];
                        string referencedSchemaName = (string)reader["PKTABLE_SCHEM"];
                        string referencedTableName = (string)reader["PKTABLE_NAME"];
                        string referencedColumnName = (string)reader["PKCOLUMN_NAME"];
                        bool isCascadeDelete = "CASCADE".EqualsIgnoreCase((string)reader["CASCADE"]);
                        string qualifiedReferencedTableName = GetQualifiedIdentifier(referencedSchemaName, referencedTableName);
                        var a = tableSource.Database;
                        ITableSourceInfo referencedTableSource = new DB2ZOSTableSourceInfo(DatabaseServices, tableSource.Database, referencedTableName, qualifiedReferencedTableName);
                        ITableSourceForeignKeyInfo foreignKeyInfo = new DB2ZOSTableSourceForeignKeyInfo(tableSource, foreignKeyName, columnName, referencedTableSource, referencedColumnName, isCascadeDelete);
                        foreignKeys.Add(foreignKeyInfo);
                    }
                }
                return foreignKeys;
            }
        }
    }
}
