/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace SampleDatabaseProvider.Introspection {

    /// <summary>
    /// Contains information about a database.
    /// </summary>
    public class DatabaseInfo : BaseDatabaseInfo {

        /// <summary>
        /// Initializes a new instance of the <see cref="DatabaseInfo"/> class.
        /// </summary>
        /// <param name="databaseServices">The database services.</param>
        /// <param name="database">The database.</param>
        public DatabaseInfo(IDatabaseServices databaseServices, string database) : base(databaseServices) {
            Database = string.IsNullOrEmpty(database) ? databaseServices.DatabaseConfiguration.DatabaseIdentifier : database;
        }

        private string Database { get; set; }

        /// <summary>
        /// Name that identifies the database
        /// </summary>
        public override string Identifier {
            get { return Database; }
        }
    }
}
