/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

namespace SampleDatabaseProvider.Introspection {

    /// <summary>
    /// Creates introspection objects from qualified names, inspecting the database only if needed.
    /// </summary>
    public class DatabaseObjectFactory : IDatabaseObjectFactory {

        protected readonly IDatabaseServices databaseServices;

        /// <summary>
        /// Initializes a new instance of the <see cref="DatabaseObjectFactory"/> class.
        /// </summary>
        /// <param name="databaseServices">The database services.</param>
        public DatabaseObjectFactory(IDatabaseServices databaseServices) {
            this.databaseServices = databaseServices;
        }

        /// <summary>
        /// Returns an object that contains information about the current database
        /// </summary>
        /// <returns>
        /// Database-specific object that implements the IDatabaseInfo interface
        /// </returns>
        public IDatabaseInfo CreateLocalDatabaseInfo() {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Returns an object that contains information about a database, inferring it from a database identifier.
        /// If the <paramref name="databaseIdentifier" /> does not contain all the required information, the remaining
        /// should be inferred from the current <see cref="T:OutSystems.HubEdition.Extensibility.Data.ConfigurationService.IRuntimeDatabaseConfiguration" />.
        /// </summary>
        /// <param name="databaseIdentifier">Unique identifier of the database</param>
        /// <returns>
        /// Database-specific object that implements the IDatabaseInfo interface
        /// </returns>
        public IDatabaseInfo CreateDatabaseInfo(string databaseIdentifier) {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Returns an object that contains information about a table source (data source in tabular format), like a database table or view,
        /// inferring both the database and table source information from a qualifiedName. If the <paramref name="qualifiedName" /> does not contain
        /// all the required information, the remaining should be inferred from the current <see cref="T:OutSystems.HubEdition.Extensibility.Data.ConfigurationService.IRuntimeDatabaseConfiguration" />.
        /// </summary>
        /// <param name="qualifiedName">Qualified identifier of the table source, including the database information</param>
        /// <returns>
        /// Database-specific object that implements the ITableSourceInfo interface
        /// </returns>
        public ITableSourceInfo CreateTableSourceInfo(string qualifiedName) {
            throw new NotImplementedException();
        }
    }
}
