/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.ConfigurationService;

namespace SampleDatabaseProvider.Configuration {

    /// <summary> 
    /// The configuration object used to create services and open connections to the database. 
    /// <remarks>We have other configuration interfaces like <see cref="IIntegrationDatabaseConfiguration" /> 
    /// that are used to specify the UI of a configuration screen.</remarks> 
    /// </summary>
    public class RuntimeDatabaseConfiguration : IRuntimeDatabaseConfiguration {

        /// <summary>
        /// Gets the database provider. It provides information about the database,
        /// and access to its services.
        /// </summary>
        public IDatabaseProvider DatabaseProvider { get; set; }

        /// <summary>
        /// The user that this configuration uses to connect to the database.
        /// </summary>
        [ConfigurationParameter]
        public string Username { get; set; }

        /// <summary>
        /// Gets the connection string that allows connecting to a database.
        /// </summary>
        [ConfigurationParameter]
        public string ConnectionString { get; set; }

        /// <summary>
        /// Gets the database identifier to be used in the configuration.
        /// </summary>
        /// <exception cref="System.NotImplementedException"></exception>
        public string DatabaseIdentifier {
            get { throw new NotImplementedException(); }
        }
    }
}
