/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OutSystems.HubEdition.DatabaseProvider.DB2ZOS.ConfigurationService
{
    /// <summary>
    /// DB2 Connection String ID's aggregator
    /// 
    /// Connection String Format
    ///        DataSource=<ip address/localhost>:<port number>; 
    ///        Database=<db name>;
    ///        UID=<userID>; 
    ///        PWD=<password>; 
    /// </summary>
    public class DB2ZOSIDs
    {
        public static readonly string USERNAME = "User Id";
        public static readonly string PASSWORD = "Password";
        public static readonly string DATA_SOURCE = "Server";
        public static readonly string DATABASE = "Database";
        public static readonly string SCHEMA = "CurrentSchema";
    }
}
