/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DMLService;

namespace SampleDatabaseProvider.DML {

    /// <summary>
    /// Class for generating the DML aggregate functions required by the applications to perform DataSet queries.
    /// </summary>
    public class DMLAggregateFunctions : BaseDMLAggregateFunctions {

        /// <summary>
        /// Initializes a new instance of the <see cref="DMLAggregateFunctions"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        internal DMLAggregateFunctions(IDMLService dmlService) : base(dmlService) {}

        /// <summary>
        /// This property represents the associated DML service.
        /// </summary>
        public new DMLService DMLService {
            get { return (DMLService)base.DMLService; }
        }
    }
}
