/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;

namespace SampleDatabaseProvider.DML {

    /// <summary>
    /// Class that represents the different kinds of entity actions supported by the platform.
    /// </summary>
    public class DMLEntityActions : BaseDMLEntityActions {

        /// <summary>
        /// Initializes a new instance of the <see cref="DMLEntityActions"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        /// <param name="tableSourceInfo">The table source information.</param>
        internal DMLEntityActions(IDMLService dmlService, ITableSourceInfo tableSourceInfo) : base(dmlService, tableSourceInfo) { }

    }
}
