/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using OutSystems.HubEdition.Extensibility.Data.DMLService;

namespace SampleDatabaseProvider.DML {

    /// <summary>
    /// Implementation of the <see>IDMLIdentifiers</see> interface that defines methods
    /// that help build DML Identifiers for columns, tables, and others.
    /// </summary>
    public class DMLIdentifiers : BaseDMLIdentifiers{

        /// <summary>
        /// Initializes a new instance of the <see cref="DMLIdentifiers"/> class.
        /// </summary>
        /// <param name="dmlService">The DML service.</param>
        internal DMLIdentifiers(IDMLService dmlService) : base(dmlService) { }

        /// <summary>
        /// Gets the maximum length of a simple (not compound) identifier. This value should be the minimum valid
        /// length for any kind of identifier (e.g. table name, parameter name)
        /// </summary>
        public override int MaxLength {
            get { throw new NotImplementedException(); }
        }
    }
}
