/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.DatabaseProvider.DB2ZOS.ConfigurationService;
using System.Data;

namespace OutSystems.HubEdition.DatabaseProvider.DB2ZOS.DMLService
{
    internal class DB2ZOSDMLIdentifiers : BaseDMLIdentifiers
    {

        private readonly string ESCAPE_CHAR = "\"";
        internal DB2ZOSDMLIdentifiers(IDMLService dmlService) : base(dmlService) { }

        public override int MaxLength { get { return 128; } }

        public override string EscapeIdentifier(string identifierName) {
            if (string.IsNullOrEmpty(identifierName))
                return string.Empty;

            string startEsc = identifierName.StartsWith(ESCAPE_CHAR) ? string.Empty : ESCAPE_CHAR;
            string endEsc = identifierName.EndsWith(ESCAPE_CHAR) ? string.Empty : ESCAPE_CHAR;

            return string.Format("{0}{1}{2}", startEsc, identifierName, endEsc);
        }
    }
}
