/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;
using OutSystems.HubEdition.Extensibility.Data.DMLService;
using OutSystems.HubEdition.Extensibility.Data.IntrospectionService;

namespace OutSystems.HubEdition.DatabaseProvider.DB2ZOS.DMLService {
    public class DB2ZOSDMLService : BaseDMLService {

        private readonly IDMLQueries queries;
        private readonly IDMLIdentifiers identifiers;
        private readonly IDMLOperators operators;
        private readonly IDMLFunctions functions;
        private readonly IDMLDefaultValues defaultValues;
        private readonly IDMLAggregateFunctions aggregateFunctions;
        private readonly IDMLSyntaxHighlightDefinitions syntaxHighlightDefinitions;

        public DB2ZOSDMLService(IDatabaseServices databaseServices)
            : base(databaseServices) {
            queries = new DB2ZOSDMLQueries(this);
            identifiers = new DB2ZOSDMLIdentifiers(this);
            operators = new DB2ZOSDMLOperators(this);
            functions = new DB2ZOSDMLFunctions(this);
            defaultValues = new DB2ZOSDMLDefaultValues(this);
            aggregateFunctions = new DB2ZOSDMLAggregateFunctions(this);
            syntaxHighlightDefinitions = new DB2ZOSDMLSyntaxHighlightDefinitions(this);
        }

        public override IDMLQueries Queries {
            get { return queries; }
        }

        public override IDMLEntityActions GetEntityActions(ITableSourceInfo tableSourceInfo) {
            return new DB2ZOSDMLEntityActions(this, tableSourceInfo);
        }

        public override IDMLIdentifiers Identifiers { get { return identifiers; } }

        public override IDMLOperators Operators { get { return operators; } }

        public override IDMLFunctions Functions { get { return functions; } }

        public override IDMLDefaultValues DefaultValues { get { return defaultValues; } }

        public override IDMLAggregateFunctions AggregateFunctions { get { return aggregateFunctions; } }

        public override IDMLSyntaxHighlightDefinitions SyntaxHighlightDefinitions { get { return syntaxHighlightDefinitions; } }
    }
}
